# Generated by Django 2.2.6 on 2020-01-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.CharField(default='this is default text of slider', max_length=255),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default='this is title', max_length=50),
        ),
    ]
