# Generated by Django 2.2.6 on 2020-01-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20200109_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=models.CharField(default='slide image must be width:950px to height:450px', max_length=255),
        ),
    ]
